// SPDX-License-Identifier: MIT

#pragma once
#ifndef LAONOS_LOADER_INCLUDE_INFO_H
#define LAONOS_LOADER_INCLUDE_INFO_H

#define OS_KERNEL_NAME "KERNEL"
#define OS_KERNEL_VME 0xfffffff800000000

#endif // LAONOS_LOADER_INCLUDE_INFO_H
